# --- COMA specific parameters ---

action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .01
epsilon_anneal_time: 1200000
mask_before_softmax: False

runner: "parallel"

buffer_size: 24
best_buffer_size: 12
batch_size_run: 10
batch_size: 12
best_batch_size: 6

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval: 600

n_sum: 40 # number of sampling for exp_q (adjustable based on # of agents)
step: 3 #steps for tree back up diagram  (adjustable based on # of agents)
comm_channel: 4 # self.d = rnn_dim // comm_channel (adjustable based on # of agents)
cut_off: 0.0002 #cut_off factor for sigmoid annealing
coeff: 0.9  # policy annealing factor
beta: 0.001


lr: 0.0005
critic_lr: 0.0005
td_lambda: 0.8

# use COMA
agent_output_type: "pi_logits"
learner: "offpg_learner"
critic_q_fn: "coma"
critic_baseline_fn: "coma"
critic_train_mode: "seq"
critic_train_reps: 1
q_nstep: 0  # 0 corresponds to default Q, 1 is r + gamma*Q, etc

name: "offpg_smac"
